### ISSUE TITLE
[퍼블리싱] 오타 수정

### ISSUE THREAD

**Issue by minsoo-web** [soraji/soraji.github.io#2]
안녕하세요, 구글링을 통해 우연히 블로그를 둘러보다 발견한 오타가 있어 이슈 남깁니다.

![스크린샷 2021-01-14 오후 5 11 11](https://user-images.githubusercontent.com/57122180/104562300-819e2500-568b-11eb-88c8-cf1de26fa4ca.png)

> 혹시나 민드는 걸 좋아하시는 게 맞다면 제가 괜한 이슈를,,,

글 잘 보고 갑니다! 감사합니다.

**Comment by soraji** [comment]
헐 민수님ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ어머나 세상에 저 지금 발견했어요...
1월에 쓰셨는데 9월에 발견한 저란 사람.... 세상에 마상에

당연히 만드는걸 좋아하는 사람이죸ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
민드는건 무슨 뜻일까요?ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ아 웃경
감사합니다>_< 언능수정해놓을게요!!!!ㅋㅋㅋㅋㅋ
아 오늘 민수님 덕분에 한참을 웃었네요 감사해요 (❁ᴗ͈ˬᴗ͈)◞

**Comment by minsoo-web** [comment]
수정된 것 확인했어요! 저도 이런 이슈를 남긴걸 깜빡하고 살았네요 ㅋㅋ큐ㅠ 좋은 하루 되세요!
